language: python

stages:
  - linting
  - test
  - build
  - deploy

before_install:
  - pip install codecov
  - |
    if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ]; then
      export PYENV_ROOT="$HOME/.pyenv"
      if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
        pushd "$PYENV_ROOT" && git pull && popd
      else
        rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
      fi
      export PYPY_VERSION="5.6.0"
      "$PYENV_ROOT/bin/pyenv" install --skip-existing "pypy-$PYPY_VERSION"
      virtualenv --python="$PYENV_ROOT/versions/pypy-$PYPY_VERSION/bin/python" "$HOME/virtualenvs/pypy-$PYPY_VERSION"
      source "$HOME/virtualenvs/pypy-$PYPY_VERSION/bin/activate"
    fi

install:
  - pip install .
script:
  - python setup.py test
after_success:
  - codecov

matrix:
  include:
  - os: windows
    language: sh
    before_install:
      - choco install python3
      - export PATH="/c/Python$TRAVIS_PYTHON_VERSION:/c/Python37/Scripts:$PATH"
      - python -m pip install --upgrade pip wheel
  - os: osx
    language: sh
    # Perform the manual steps on osx to install python3 and activate venv
    before_install:
      - brew update
      - brew upgrade python3
      - python3 -m pip install virtualenv
      - virtualenv venv -p python3
      - source venv/bin/activate
jobs:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
    - python: pypy
    - python: pypy3
    - stage: linting
      python: 3.6
      before_script: skip
      after_script: skip
      script:
        - python setup.py lint || exit $(($? & 35))
    - stage: build
      python: 3.6
      before_script: skip
      after_script: skip
      script:
        - python setup.py sdist
# TODO: implement
#    - stage: deploy
#      deploy:
#        provider: pypi
#        user: boxed
#        password:
#          secure:
#        on:
#          python: 3.6
#          tags: true
#          repo: nklapste/muckup
